# Generated by Django 5.1.1 on 2024-11-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='wallet_balance',
        ),
    ]
