# Generated by Django 5.1.1 on 2024-11-05 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_client_wallet_balance'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
    ]
