# Generated by Django 5.1.1 on 2024-11-18 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_client_managers_remove_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='otp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
