# Generated by Django 5.1.1 on 2024-11-19 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_client_otp_client_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
