version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app
      - media_volume:/media  # انتقال media خارج از /app
      - static_volume:/app/staticfiles
    depends_on:
      - db
    environment:
      - DEBUG=False
      - SECRET_KEY="django-insecure-ke0$uicco09-)3a&6!sjwlj890ws_fe&7k_aq-=vzibs_d=j-l"
      - DATABASE_URL=postgresql://postgres:1111@postgress-ekr-service:5432/postgreserd_db
    networks:
      - app_network

  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - app_network

  nginx:
    image: nginx:1.21
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/media  # این‌جا هم مسیر جدید media را تعریف می‌کنیم
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
