# Generated by Django 5.1.7 on 2025-04-13 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_delete_wallettransaction'),
        ('service', '0004_userservicerequest_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
            preserve_default=False,
        ),
    ]
