# Generated by Django 5.1.7 on 2025-04-16 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_service'),
        ('service', '0004_userservicerequest_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='service',
        ),
        migrations.AddField(
            model_name='payment',
            name='service_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.userservicerequest'),
            preserve_default=False,
        ),
    ]
