# Generated by Django 5.1.3 on 2025-03-17 07:10

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('homepage', models.BooleanField(default=False)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('summery', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'permissions': [('can_view_post', 'Can view post')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment')),
            ],
        ),
    ]
