# Generated by Django 5.1.1 on 2024-12-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_view_post', 'Can view post')]},
        ),
    ]
