# Generated by Django 5.1.1 on 2024-12-05 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='فقط حروف، اعداد، خط فاصله و خط زیر مجاز هستند.', regex='^[\\w-]+$|^[آ-یءچپژگک\\s-]+$')]),
        ),
    ]
