# Generated by Django 5.1.1 on 2024-09-23 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('call', 'تماس تلفنی'), ('text', 'پیام متنی'), ('complaint', 'تنظیم شکایت')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_days', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='UserServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
