# Generated by Django 5.1.7 on 2025-04-11 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='service_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx', 'zip'])]),
        ),
    ]
