# Generated by Django 5.1.1 on 2024-11-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_freeform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='userservicerequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userservicerequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userservicerequest',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('call', 'تماس تلفنی'), ('text', 'پیام متنی'), ('complaint', 'تنظیم شکایت'), ('ekhtesasi', 'اختصاصی')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userservicerequest',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
