# Generated by Django 5.1.7 on 2025-04-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_userservicerequest_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicerequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
