# Generated by Django 5.2 on 2025-04-25 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_userservicerequest_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userservicerequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
